server:
  port: 8090

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/bkmkdb?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    auto-commit: true
    minimum-idle: 5
    maximum-pool-size: 15
    idle-timeout: 30000
    pool-name: DatebookHikariCP
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1
  data:
    mongodb:
      uri: mongodb://localhost:27017/user
  mvc:
    view:
     prefix: /
     suffix: .html
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
        sshutdown-timeout: 100ms
    host: localhost
    port: 6379
    timeout: 10000ms
  mail:
    host: smtp.qq.com
    username: jiangcy2018@foxmail.com
    password: zcmzlmasevkwifij
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mappers/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.eve.bookmarks.entitys.po  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count:countSql

mail:
  toaddress: 13721074873@163.com